/** Durable job-run ledger so Admin can see what background processing is doing. */
var KPI_ACTIVE_JOB_RUN_ID_ = '';
function kpiRecoverStaleJobRunsUnlocked_(){var rows=kpiReadObjects_(KPI_CONST.SHEETS.JOB_RUNS,KPI_HEADERS.PC_KPIJobRuns),now=Date.now(),iso=kpiNowIso_(),recovered=0;for(var i=Math.max(0,rows.length-100);i<rows.length;i++){var r=rows[i],started=new Date(r.StartedAt);if(String(r.Status)!=='RUNNING'||!isFinite(started.getTime())||now-started.getTime()<=15*60000)continue;r.CompletedAt=iso;r.Status='FAILED';r.Stage='STALE_TIMEOUT';r.Message='Execution ก่อนหน้าค้าง/สิ้นสุดโดยไม่ปิด Job Ledger';r.ErrorCode='KPI_JOB_STALE';r.ErrorMessage='Marked stale after more than 15 minutes';kpiUpdateRow_(KPI_CONST.SHEETS.JOB_RUNS,KPI_HEADERS.PC_KPIJobRuns,i+2,r);recovered++;}return recovered;}
function kpiAppendJobRun_(row){ var lock=LockService.getScriptLock();if(!lock.tryLock(5000))throw new Error('KPI_JOB_LEDGER_BUSY');try{kpiRecoverStaleJobRunsUnlocked_();kpiAppendObjects_(KPI_CONST.SHEETS.JOB_RUNS,KPI_HEADERS.PC_KPIJobRuns,[row]);return row.JobRunId;}finally{lock.releaseLock();} }
function kpiPatchJobRunUnlocked_(id,patch){ var rows=kpiReadObjects_(KPI_CONST.SHEETS.JOB_RUNS,KPI_HEADERS.PC_KPIJobRuns); for(var i=rows.length-1;i>=0;i--){ if(String(rows[i].JobRunId)===String(id)){ Object.keys(patch||{}).forEach(function(k){rows[i][k]=patch[k];}); kpiUpdateRow_(KPI_CONST.SHEETS.JOB_RUNS,KPI_HEADERS.PC_KPIJobRuns,i+2,rows[i]); return true; }} return false; }
function kpiPatchJobRun_(id,patch){ var lock=LockService.getScriptLock();if(!lock.tryLock(5000))return false;try{return kpiPatchJobRunUnlocked_(id,patch);}finally{lock.releaseLock();} }
function kpiJobStage_(stage,message,processed){ if(!KPI_ACTIVE_JOB_RUN_ID_)return false;var patch={Stage:String(stage||''),Message:String(message||'กำลังดำเนินการ')};if(processed!=null)patch.ProcessedCount=Number(processed)||0;try{console.log('[KPI JOB '+KPI_ACTIVE_JOB_RUN_ID_+'] '+patch.Stage+' — '+patch.Message);return kpiPatchJobRunUnlocked_(KPI_ACTIVE_JOB_RUN_ID_,patch);}catch(ignored){return false;} }
function kpiJobCounts_(result){ result=result||{}; return {ProcessedCount:Number(result.processed||result.reviewMetrics||result.rows||0),AddedCount:Number(result.eventsAdded||result.added||0),UpdatedCount:Number(result.updated||result.assignments&&result.assignments.completed||0),PrunedCount:Number(result.prunedEvents||result.pruned||0)}; }
function kpiRunTrackedJob_(jobType,triggerType,fn){
  kpiAssertSatelliteRunner_(); var id=Utilities.getUuid(),start=kpiNowIso_(),runner=KPI_SATELLITE.REQUIRED_RUNNER_EMAIL;
  kpiAppendJobRun_({JobRunId:id,JobType:jobType,TriggerType:triggerType||'SYSTEM',StartedAt:start,CompletedAt:'',Status:'RUNNING',Stage:'STARTED',ProcessedCount:0,AddedCount:0,UpdatedCount:0,PrunedCount:0,Message:'กำลังดำเนินการ',ErrorCode:'',ErrorMessage:'',RunnerEmail:runner,ModuleVersion:KPI_CONST.VERSION});
  KPI_ACTIVE_JOB_RUN_ID_=id;
  try { var result=fn(),c=kpiJobCounts_(result); kpiPatchJobRun_(id,{CompletedAt:kpiNowIso_(),Status:(result&&result.skipped)?'SKIPPED':'SUCCESS',Stage:'COMPLETED',ProcessedCount:c.ProcessedCount,AddedCount:c.AddedCount,UpdatedCount:c.UpdatedCount,PrunedCount:c.PrunedCount,Message:(result&&result.skipped)?String(result.skipped):'เสร็จสมบูรณ์'}); kpiPruneJobRuns_(); return result; }
  catch(e){ kpiPatchJobRun_(id,{CompletedAt:kpiNowIso_(),Status:'FAILED',Stage:'ERROR',Message:'เกิดข้อผิดพลาด',ErrorCode:String(e&&e.code||'KPI_JOB_ERROR'),ErrorMessage:String(e&&e.message||e)}); throw e; }
  finally { KPI_ACTIVE_JOB_RUN_ID_=''; }
}
function kpiPruneJobRuns_(){ var lock=LockService.getScriptLock();if(!lock.tryLock(5000))return 0;try{var rows=kpiReadObjects_(KPI_CONST.SHEETS.JOB_RUNS,KPI_HEADERS.PC_KPIJobRuns),max=KPI_SATELLITE.JOB_RETENTION_ROWS;if(rows.length<=max)return 0;var kept=rows.slice(rows.length-max);kpiReplaceObjects_(KPI_CONST.SHEETS.JOB_RUNS,KPI_HEADERS.PC_KPIJobRuns,kept);return rows.length-kept.length;}finally{lock.releaseLock();} }
function kpiLatestJobRuns_(limit){ var rows=kpiReadObjects_(KPI_CONST.SHEETS.JOB_RUNS,KPI_HEADERS.PC_KPIJobRuns),now=Date.now(),staleMs=15*60000; return rows.slice(-Math.max(1,Number(limit)||12)).reverse().map(function(r){var started=new Date(r.StartedAt),status=String(r.Status||''),stale=status==='RUNNING'&&isFinite(started.getTime())&&(now-started.getTime()>staleMs);return{jobRunId:String(r.JobRunId||''),jobType:String(r.JobType||''),triggerType:String(r.TriggerType||''),startedAt:String(r.StartedAt||''),completedAt:String(r.CompletedAt||''),status:status,displayStatus:stale?'STALE':status,stale:stale,stage:String(r.Stage||''),processedCount:Number(r.ProcessedCount||0),addedCount:Number(r.AddedCount||0),updatedCount:Number(r.UpdatedCount||0),prunedCount:Number(r.PrunedCount||0),message:stale?'งานค้างเกิน 15 นาที — ควรตรวจ Execution log':String(r.Message||''),errorCode:String(r.ErrorCode||''),errorMessage:String(r.ErrorMessage||'')};}); }
function getAdminKpiSystemStatus_(){ requirePrecheckAdmin_(); var health=runKpiHealthCheckCore_(); return {ok:health.ok,moduleVersion:KPI_CONST.VERSION,runner:KPI_SATELLITE.REQUIRED_RUNNER_EMAIL,health:health,jobs:kpiLatestJobRuns_(15)}; }

/** Installable trigger entry points. Each job is visible in PC_KPIJobRuns. */
function kpiReconcileTrigger(){ return kpiRunTrackedJob_('RECONCILE','TRIGGER',runKpiReconcileCore_); }
function kpiQueueSnapshotTrigger(){ return kpiRunTrackedJob_('QUEUE_SNAPSHOT','TRIGGER',takeKpiQueueSnapshotCore_); }
function kpiDailyAggregateTrigger(){ return kpiRunTrackedJob_('DAILY_AGGREGATE','TRIGGER',rebuildKpiDailyAggregatesCore_); }
